#.travis.yml

language: node_js
node_js:
  - "6.9"

cache:
  directories:
    - node_modules

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod

after_success:
  - ng serve

deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: heavencross/Angular4
  bucket: travisdeploy
  region: us-west-2
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: travisdeploy
  key: latest.zip
  bundle_type: zip
  application: nodejsapp
  deployment_group: nodejsappGroup
  region: us-west-2
  on: *2
script:
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip
