export const ENTITIES = {
  'serviceResponseStatus': {
    'statusCode': 'RC-S013',
    'statusMessage': 'Successfully fetching relationships',
    'statusType': 'SUCCESS',
    'languageCode': 'ENG',
    'traceID': '00e5148d-c90a-44fe-abfb-c14d57338be0',
    'errorSeverity': 'NA',
    'displayOnUI': 'N'
  },
  'canAccessRequest': true,
  'userType': 'CONSUMER',
  'relationshipList': [
    {
      'serialNumber': null,
      'rid': 76481510,
      'r2id': null,
      'providerid': 100000489,
      'consumerid': null,
      'leoiid': 123587989,
      'provider': 'IM C1',
      'consumer': '--',
      'leoi': '\'Accelerated\' High Yield Income Fund, Ltd.',
      'status': null,
      'isprovidertoleoi': null,
      'endDate': null,
      'canOfferAccess': false,
      'provConsInd': 'CONSUMER',
      'leoiOtherName': '--',
      'leoiOtherNameId': null,
      'aliasSearchInd': null,
      'canManageRelationship': null,
      'groupedRelationship': [
        {
          'serialNumber': 916,
          'rid': 76481510,
          'r2id': 76481540,
          'providerid': 100000489,
          'consumerid': 100000619,
          'leoiid': 123587989,
          'provider': 'IM C1',
          'consumer': 'State Street Global Advisors Limited',
          'leoi': '\'Accelerated\' High Yield Income Fund, Ltd.',
          'status': 'Active',
          'isprovidertoleoi': null,
          'endDate': null,
          'canOfferAccess': false,
          'provConsInd': 'CONSUMER',
          'leoiOtherName': '--',
          'leoiOtherNameId': null,
          'aliasSearchInd': null,
          'canManageRelationship': true,
          'groupedRelationship': null,
          'services': 'Public KYC Premium',
          'country': '--',
          'formationStatusCd': 'ACTIVE',
          'formationStatusDesc': 'Active',
          'isNew': false,
          'serviceCd': 'PKYC_PREMIUM',
          'sourceTypeCd': 'PROVIDER',
          'canInitiateServiceRequest': true
        },
        {
          'serialNumber': 917,
          'rid': 76481510,
          'r2id': 76481540,
          'providerid': 100000489,
          'consumerid': 100000619,
          'leoiid': 123587989,
          'provider': 'IM C1',
          'consumer': 'State Street Global Advisors Limited',
          'leoi': '\'Accelerated\' High Yield Income Fund, Ltd.',
          'status': 'Active',
          'isprovidertoleoi': null,
          'endDate': null,
          'canOfferAccess': false,
          'provConsInd': 'CONSUMER',
          'leoiOtherName': '--',
          'leoiOtherNameId': null,
          'aliasSearchInd': null,
          'canManageRelationship': true,
          'groupedRelationship': null,
          'services': 'Public KYC',
          'country': '--',
          'formationStatusCd': 'ACTIVE',
          'formationStatusDesc': 'Active',
          'isNew': false,
          'serviceCd': 'PKYC',
          'sourceTypeCd': 'PROVIDER',
          'canInitiateServiceRequest': true
        },
        {
          'serialNumber': 918,
          'rid': 76481510,
          'r2id': 76481540,
          'providerid': 100000489,
          'consumerid': 100000619,
          'leoiid': 123587989,
          'provider': 'IM C1',
          'consumer': 'State Street Global Advisors Limited',
          'leoi': '\'Accelerated\' High Yield Income Fund, Ltd.',
          'status': 'Active',
          'isprovidertoleoi': null,
          'endDate': null,
          'canOfferAccess': false,
          'provConsInd': 'CONSUMER',
          'leoiOtherName': '--',
          'leoiOtherNameId': null,
          'aliasSearchInd': null,
          'canManageRelationship': true,
          'groupedRelationship': null,
          'services': 'Base Relationship',
          'country': '--',
          'formationStatusCd': 'ACTIVE',
          'formationStatusDesc': 'Active',
          'isNew': false,
          'serviceCd': 'BASE_REL',
          'sourceTypeCd': 'PROVIDER',
          'canInitiateServiceRequest': true
        }
      ],
      'services': '--',
      'country': '--',
      'formationStatusCd': 'ACTIVE',
      'formationStatusDesc': 'Active',
      'isNew': null,
      'serviceCd': null,
      'sourceTypeCd': null,
      'canInitiateServiceRequest': false
    },
    {
      'serialNumber': 919,
      'rid': 76301140,
      'r2id': 76301180,
      'providerid': 7,
      'consumerid': 100000619,
      'leoiid': 119237449,
      'provider': 'Clarient',
      'consumer': 'State Street Global Advisors Limited',
      'leoi': '\'Almatinskie Elektricheskie Stantsii\' AO',
      'status': 'Active',
      'isprovidertoleoi': null,
      'endDate': null,
      'canOfferAccess': false,
      'provConsInd': 'CONSUMER',
      'leoiOtherName': '--',
      'leoiOtherNameId': null,
      'aliasSearchInd': null,
      'canManageRelationship': true,
      'groupedRelationship': null,
      'services': 'Public KYC Premium',
      'country': '--',
      'formationStatusCd': null,
      'formationStatusDesc': null,
      'isNew': false,
      'serviceCd': 'PKYC_PREMIUM',
      'sourceTypeCd': 'PROVIDER',
      'canInitiateServiceRequest': true
    },
    {
      'serialNumber': 879,
      'rid': 76477340,
      'r2id': null,
      'providerid': 100000619,
      'consumerid': null,
      'leoiid': 123563099,
      'provider': 'State Street Global Advisors Limited',
      'consumer': '--',
      'leoi': '\'Balkanbank\' AD',
      'status': 'Active',
      'isprovidertoleoi': 'Y',
      'endDate': null,
      'canOfferAccess': true,
      'provConsInd': 'PROVIDER',
      'leoiOtherName': '--',
      'leoiOtherNameId': null,
      'aliasSearchInd': null,
      'canManageRelationship': false,
      'groupedRelationship': [
        {
          'serialNumber': 1,
          'rid': 76477340,
          'r2id': 76496510,
          'providerid': 100000619,
          'consumerid': 100000559,
          'leoiid': 123563099,
          'provider': 'State Street Global Advisors Limited',
          'consumer': 'Bank AA1',
          'leoi': '\'Balkanbank\' AD',
          'status': 'Active',
          'isprovidertoleoi': 'N',
          'endDate': null,
          'canOfferAccess': false,
          'provConsInd': 'PROVIDER',
          'leoiOtherName': '--',
          'leoiOtherNameId': null,
          'aliasSearchInd': null,
          'canManageRelationship': true,
          'groupedRelationship': null,
          'services': 'Public KYC',
          'country': '--',
          'formationStatusCd': 'CLSD_DISSOLVED',
          'formationStatusDesc': 'Closed/Dissolved',
          'isNew': false,
          'serviceCd': 'PKYC',
          'sourceTypeCd': 'PROVIDER',
          'canInitiateServiceRequest': false
        },
        {
          'serialNumber': 4,
          'rid': 76477340,
          'r2id': 76496510,
          'providerid': 100000619,
          'consumerid': 100000559,
          'leoiid': 123563099,
          'provider': 'State Street Global Advisors Limited',
          'consumer': 'Bank AA1',
          'leoi': '\'Balkanbank\' AD',
          'status': 'Active',
          'isprovidertoleoi': 'N',
          'endDate': null,
          'canOfferAccess': false,
          'provConsInd': 'PROVIDER',
          'leoiOtherName': '--',
          'leoiOtherNameId': null,
          'aliasSearchInd': null,
          'canManageRelationship': true,
          'groupedRelationship': null,
          'services': 'Base Relationship',
          'country': '--',
          'formationStatusCd': 'CLSD_DISSOLVED',
          'formationStatusDesc': 'Closed/Dissolved',
          'isNew': false,
          'serviceCd': 'BASE_REL',
          'sourceTypeCd': 'PROVIDER',
          'canInitiateServiceRequest': false
        },
        {
          'serialNumber': 2,
          'rid': 76477340,
          'r2id': 76477360,
          'providerid': 100000619,
          'consumerid': 7,
          'leoiid': 123563099,
          'provider': 'State Street Global Advisors Limited',
          'consumer': 'Clarient',
          'leoi': '\'Balkanbank\' AD',
          'status': 'Active',
          'isprovidertoleoi': 'N',
          'endDate': null,
          'canOfferAccess': false,
          'provConsInd': 'PROVIDER',
          'leoiOtherName': '--',
          'leoiOtherNameId': null,
          'aliasSearchInd': null,
          'canManageRelationship': true,
          'groupedRelationship': null,
          'services': 'Public KYC',
          'country': '--',
          'formationStatusCd': 'CLSD_DISSOLVED',
          'formationStatusDesc': 'Closed/Dissolved',
          'isNew': false,
          'serviceCd': 'PKYC',
          'sourceTypeCd': 'PROVIDER',
          'canInitiateServiceRequest': false
        },
        {
          'serialNumber': 3,
          'rid': 76477340,
          'r2id': 76477360,
          'providerid': 100000619,
          'consumerid': 7,
          'leoiid': 123563099,
          'provider': 'State Street Global Advisors Limited',
          'consumer': 'Clarient',
          'leoi': '\'Balkanbank\' AD',
          'status': 'Active',
          'isprovidertoleoi': 'N',
          'endDate': null,
          'canOfferAccess': false,
          'provConsInd': 'PROVIDER',
          'leoiOtherName': '--',
          'leoiOtherNameId': null,
          'aliasSearchInd': null,
          'canManageRelationship': true,
          'groupedRelationship': null,
          'services': 'Base Relationship',
          'country': '--',
          'formationStatusCd': 'CLSD_DISSOLVED',
          'formationStatusDesc': 'Closed/Dissolved',
          'isNew': false,
          'serviceCd': 'BASE_REL',
          'sourceTypeCd': 'PROVIDER',
          'canInitiateServiceRequest': false
        }
      ],
      'services': '--',
      'country': '--',
      'formationStatusCd': 'CLSD_DISSOLVED',
      'formationStatusDesc': 'Closed/Dissolved',
      'isNew': false,
      'serviceCd': null,
      'sourceTypeCd': 'PROVIDER',
      'canInitiateServiceRequest': false
    },
    {
      'serialNumber': 920,
      'rid': 76477350,
      'r2id': 76489570,
      'providerid': 7,
      'consumerid': 100000619,
      'leoiid': 123563109,
      'provider': 'Clarient',
      'consumer': 'State Street Global Advisors Limited',
      'leoi': '\'Balkanbank\' AD',
      'status': 'Active',
      'isprovidertoleoi': null,
      'endDate': null,
      'canOfferAccess': false,
      'provConsInd': 'CONSUMER',
      'leoiOtherName': '--',
      'leoiOtherNameId': null,
      'aliasSearchInd': null,
      'canManageRelationship': true,
      'groupedRelationship': null,
      'services': 'Public KYC',
      'country': '--',
      'formationStatusCd': null,
      'formationStatusDesc': null,
      'isNew': false,
      'serviceCd': 'PKYC',
      'sourceTypeCd': 'PROVIDER',
      'canInitiateServiceRequest': true
    },
    {
      'serialNumber': 921,
      'rid': 75914160,
      'r2id': 75914200,
      'providerid': 7,
      'consumerid': 100000629,
      'leoiid': 113087489,
      'provider': 'Clarient',
      'consumer': 'ABC Fund Manager 1',
      'leoi': '\'Bero Polska\' Spółka Z Ograniczoną Odpowiedzialnością',
      'status': 'Active',
      'isprovidertoleoi': null,
      'endDate': null,
      'canOfferAccess': false,
      'provConsInd': 'CONSUMER',
      'leoiOtherName': '--',
      'leoiOtherNameId': null,
      'aliasSearchInd': null,
      'canManageRelationship': true,
      'groupedRelationship': null,
      'services': 'Public KYC Premium',
      'country': '--',
      'formationStatusCd': null,
      'formationStatusDesc': null,
      'isNew': false,
      'serviceCd': 'PKYC_PREMIUM',
      'sourceTypeCd': 'PROVIDER',
      'canInitiateServiceRequest': true
    },
    {
      'serialNumber': 922,
      'rid': 76023450,
      'r2id': 76023480,
      'providerid': 7,
      'consumerid': 100000629,
      'leoiid': 113764879,
      'provider': 'Clarient',
      'consumer': 'ABC Fund Manager 1',
      'leoi': '\'Blount\' OOO',
      'status': 'Active',
      'isprovidertoleoi': null,
      'endDate': null,
      'canOfferAccess': false,
      'provConsInd': 'CONSUMER',
      'leoiOtherName': '--',
      'leoiOtherNameId': null,
      'aliasSearchInd': null,
      'canManageRelationship': true,
      'groupedRelationship': null,
      'services': 'Public KYC Premium',
      'country': '--',
      'formationStatusCd': null,
      'formationStatusDesc': null,
      'isNew': false,
      'serviceCd': 'PKYC_PREMIUM',
      'sourceTypeCd': 'PROVIDER',
      'canInitiateServiceRequest': true
    },
    {
      'serialNumber': 923,
      'rid': 75927880,
      'r2id': 76238450,
      'providerid': 100000559,
      'consumerid': 100000629,
      'leoiid': 113187719,
      'provider': 'Bank AA1',
      'consumer': 'ABC Fund Manager 1',
      'leoi': '\'BOA Flexible Solutions\' SAS',
      'status': 'Active',
      'isprovidertoleoi': null,
      'endDate': null,
      'canOfferAccess': false,
      'provConsInd': 'CONSUMER',
      'leoiOtherName': '--',
      'leoiOtherNameId': null,
      'aliasSearchInd': null,
      'canManageRelationship': true,
      'groupedRelationship': null,
      'services': 'Base Relationship',
      'country': '--',
      'formationStatusCd': null,
      'formationStatusDesc': null,
      'isNew': false,
      'serviceCd': 'BASE_REL',
      'sourceTypeCd': 'PROVIDER',
      'canInitiateServiceRequest': true
    },
    {
      'serialNumber': 924,
      'rid': 76313190,
      'r2id': 76313230,
      'providerid': 7,
      'consumerid': 100000619,
      'leoiid': 119262169,
      'provider': 'Clarient',
      'consumer': 'State Street Global Advisors Limited',
      'leoi': '\'Cheboksary Cable Plant \'Chuvashkabel\' AO',
      'status': 'Active',
      'isprovidertoleoi': null,
      'endDate': null,
      'canOfferAccess': false,
      'provConsInd': 'CONSUMER',
      'leoiOtherName': '--',
      'leoiOtherNameId': null,
      'aliasSearchInd': null,
      'canManageRelationship': true,
      'groupedRelationship': null,
      'services': 'Public KYC Premium',
      'country': '--',
      'formationStatusCd': null,
      'formationStatusDesc': null,
      'isNew': false,
      'serviceCd': 'PKYC_PREMIUM',
      'sourceTypeCd': 'PROVIDER',
      'canInitiateServiceRequest': true
    },
    {
      'serialNumber': 805,
      'rid': 76036300,
      'r2id': null,
      'providerid': 100000619,
      'consumerid': null,
      'leoiid': 115040209,
      'provider': 'State Street Global Advisors Limited',
      'consumer': '--',
      'leoi': '\'Drafter\'',
      'status': 'Active',
      'isprovidertoleoi': 'Y',
      'endDate': null,
      'canOfferAccess': true,
      'provConsInd': 'PROVIDER',
      'leoiOtherName': '--',
      'leoiOtherNameId': null,
      'aliasSearchInd': null,
      'canManageRelationship': false,
      'groupedRelationship': [
        {
          'serialNumber': 5,
          'rid': 76036300,
          'r2id': 76490930,
          'providerid': 100000619,
          'consumerid': 7,
          'leoiid': 115040209,
          'provider': 'State Street Global Advisors Limited',
          'consumer': 'Clarient',
          'leoi': '\'Drafter\'',
          'status': 'Active',
          'isprovidertoleoi': 'N',
          'endDate': null,
          'canOfferAccess': false,
          'provConsInd': 'PROVIDER',
          'leoiOtherName': '--',
          'leoiOtherNameId': null,
          'aliasSearchInd': null,
          'canManageRelationship': true,
          'groupedRelationship': null,
          'services': 'Public KYC',
          'country': '--',
          'formationStatusCd': 'ACTIVE',
          'formationStatusDesc': 'Active',
          'isNew': false,
          'serviceCd': 'PKYC',
          'sourceTypeCd': 'PROVIDER',
          'canInitiateServiceRequest': false
        },
        {
          'serialNumber': 6,
          'rid': 76036300,
          'r2id': 76490930,
          'providerid': 100000619,
          'consumerid': 7,
          'leoiid': 115040209,
          'provider': 'State Street Global Advisors Limited',
          'consumer': 'Clarient',
          'leoi': '\'Drafter\'',
          'status': 'Active',
          'isprovidertoleoi': 'N',
          'endDate': null,
          'canOfferAccess': false,
          'provConsInd': 'PROVIDER',
          'leoiOtherName': '--',
          'leoiOtherNameId': null,
          'aliasSearchInd': null,
          'canManageRelationship': true,
          'groupedRelationship': null,
          'services': 'Base Relationship',
          'country': '--',
          'formationStatusCd': 'ACTIVE',
          'formationStatusDesc': 'Active',
          'isNew': false,
          'serviceCd': 'BASE_REL',
          'sourceTypeCd': 'PROVIDER',
          'canInitiateServiceRequest': false
        }
      ],
      'services': '--',
      'country': '--',
      'formationStatusCd': 'ACTIVE',
      'formationStatusDesc': 'Active',
      'isNew': false,
      'serviceCd': null,
      'sourceTypeCd': 'PROVIDER',
      'canInitiateServiceRequest': false
    },
    {
      'serialNumber': 925,
      'rid': 76342070,
      'r2id': 76342090,
      'providerid': 7,
      'consumerid': 100000619,
      'leoiid': 119322989,
      'provider': 'Clarient',
      'consumer': 'State Street Global Advisors Limited',
      'leoi': '\'Electrolux Poland\' Spółka Z Ograniczoną Odpowiedzialnością',
      'status': 'Active',
      'isprovidertoleoi': null,
      'endDate': null,
      'canOfferAccess': false,
      'provConsInd': 'CONSUMER',
      'leoiOtherName': '--',
      'leoiOtherNameId': null,
      'aliasSearchInd': null,
      'canManageRelationship': true,
      'groupedRelationship': null,
      'services': 'Public KYC Premium',
      'country': '--',
      'formationStatusCd': null,
      'formationStatusDesc': null,
      'isNew': false,
      'serviceCd': 'PKYC_PREMIUM',
      'sourceTypeCd': 'PROVIDER',
      'canInitiateServiceRequest': true
    },
    {
      'serialNumber': 926,
      'rid': 76016880,
      'r2id': 76016900,
      'providerid': 7,
      'consumerid': 100000629,
      'leoiid': 113758309,
      'provider': 'Clarient',
      'consumer': 'ABC Fund Manager 1',
      'leoi': '\'Europol 1\' Spółka Z Ograniczoną Odpowiedzialnością',
      'status': 'Active',
      'isprovidertoleoi': null,
      'endDate': null,
      'canOfferAccess': false,
      'provConsInd': 'CONSUMER',
      'leoiOtherName': '--',
      'leoiOtherNameId': null,
      'aliasSearchInd': null,
      'canManageRelationship': true,
      'groupedRelationship': null,
      'services': 'Public KYC Premium',
      'country': '--',
      'formationStatusCd': null,
      'formationStatusDesc': null,
      'isNew': false,
      'serviceCd': 'PKYC_PREMIUM',
      'sourceTypeCd': 'PROVIDER',
      'canInitiateServiceRequest': true
    },
    {
      'serialNumber': 885,
      'rid': 76486670,
      'r2id': null,
      'providerid': 100000619,
      'consumerid': null,
      'leoiid': 125088439,
      'provider': 'State Street Global Advisors Limited',
      'consumer': '--',
      'leoi': '\'FMC Eurasia\' LLC',
      'status': 'Active',
      'isprovidertoleoi': 'Y',
      'endDate': null,
      'canOfferAccess': true,
      'provConsInd': 'PROVIDER',
      'leoiOtherName': '--',
      'leoiOtherNameId': null,
      'aliasSearchInd': null,
      'canManageRelationship': false,
      'groupedRelationship': [
        {
          'serialNumber': 7,
          'rid': 76486670,
          'r2id': 76486680,
          'providerid': 100000619,
          'consumerid': 7,
          'leoiid': 125088439,
          'provider': 'State Street Global Advisors Limited',
          'consumer': 'Clarient',
          'leoi': '\'FMC Eurasia\' LLC',
          'status': 'Active',
          'isprovidertoleoi': 'N',
          'endDate': null,
          'canOfferAccess': false,
          'provConsInd': 'PROVIDER',
          'leoiOtherName': '--',
          'leoiOtherNameId': null,
          'aliasSearchInd': null,
          'canManageRelationship': true,
          'groupedRelationship': null,
          'services': 'Public KYC',
          'country': '--',
          'formationStatusCd': 'ACTIVE',
          'formationStatusDesc': 'Active',
          'isNew': false,
          'serviceCd': 'PKYC',
          'sourceTypeCd': 'PROVIDER',
          'canInitiateServiceRequest': false
        },
        {
          'serialNumber': 8,
          'rid': 76486670,
          'r2id': 76486680,
          'providerid': 100000619,
          'consumerid': 7,
          'leoiid': 125088439,
          'provider': 'State Street Global Advisors Limited',
          'consumer': 'Clarient',
          'leoi': '\'FMC Eurasia\' LLC',
          'status': 'Active',
          'isprovidertoleoi': 'N',
          'endDate': null,
          'canOfferAccess': false,
          'provConsInd': 'PROVIDER',
          'leoiOtherName': '--',
          'leoiOtherNameId': null,
          'aliasSearchInd': null,
          'canManageRelationship': true,
          'groupedRelationship': null,
          'services': 'Base Relationship',
          'country': '--',
          'formationStatusCd': 'ACTIVE',
          'formationStatusDesc': 'Active',
          'isNew': false,
          'serviceCd': 'BASE_REL',
          'sourceTypeCd': 'PROVIDER',
          'canInitiateServiceRequest': false
        }
      ],
      'services': '--',
      'country': '--',
      'formationStatusCd': 'ACTIVE',
      'formationStatusDesc': 'Active',
      'isNew': false,
      'serviceCd': null,
      'sourceTypeCd': 'PROVIDER',
      'canInitiateServiceRequest': false
    },
    {
      'serialNumber': 927,
      'rid': 76376540,
      'r2id': 76489920,
      'providerid': 7,
      'consumerid': 100000619,
      'leoiid': 119617569,
      'provider': 'Clarient',
      'consumer': 'State Street Global Advisors Limited',
      'leoi': '\'FMC Eurasia\' LLC',
      'status': 'Active',
      'isprovidertoleoi': null,
      'endDate': null,
      'canOfferAccess': false,
      'provConsInd': 'CONSUMER',
      'leoiOtherName': '--',
      'leoiOtherNameId': null,
      'aliasSearchInd': null,
      'canManageRelationship': true,
      'groupedRelationship': null,
      'services': 'Public KYC',
      'country': '--',
      'formationStatusCd': null,
      'formationStatusDesc': null,
      'isNew': false,
      'serviceCd': 'PKYC',
      'sourceTypeCd': 'PROVIDER',
      'canInitiateServiceRequest': true
    },
    {
      'serialNumber': 928,
      'rid': 76299550,
      'r2id': 76299580,
      'providerid': 7,
      'consumerid': 100000619,
      'leoiid': 119233999,
      'provider': 'Clarient',
      'consumer': 'State Street Global Advisors Limited',
      'leoi': '\'Fuldom\' Spółka Z Ograniczoną Odpowiedzialnością',
      'status': 'Active',
      'isprovidertoleoi': null,
      'endDate': null,
      'canOfferAccess': false,
      'provConsInd': 'CONSUMER',
      'leoiOtherName': '--',
      'leoiOtherNameId': null,
      'aliasSearchInd': null,
      'canManageRelationship': true,
      'groupedRelationship': null,
      'services': 'Public KYC Premium',
      'country': '--',
      'formationStatusCd': null,
      'formationStatusDesc': null,
      'isNew': false,
      'serviceCd': 'PKYC_PREMIUM',
      'sourceTypeCd': 'PROVIDER',
      'canInitiateServiceRequest': true
    },
    {
      'serialNumber': 804,
      'rid': 76036280,
      'r2id': null,
      'providerid': 100000619,
      'consumerid': null,
      'leoiid': 115040179,
      'provider': 'State Street Global Advisors Limited',
      'consumer': '--',
      'leoi': '\'Information Logic\'',
      'status': 'Active',
      'isprovidertoleoi': 'Y',
      'endDate': null,
      'canOfferAccess': true,
      'provConsInd': 'PROVIDER',
      'leoiOtherName': '--',
      'leoiOtherNameId': null,
      'aliasSearchInd': null,
      'canManageRelationship': false,
      'groupedRelationship': [
        {
          'serialNumber': 9,
          'rid': 76036280,
          'r2id': 76099630,
          'providerid': 100000619,
          'consumerid': 100000539,
          'leoiid': 115040179,
          'provider': 'State Street Global Advisors Limited',
          'consumer': 'IM E2',
          'leoi': '\'Information Logic\'',
          'status': 'Active',
          'isprovidertoleoi': 'N',
          'endDate': null,
          'canOfferAccess': false,
          'provConsInd': 'PROVIDER',
          'leoiOtherName': '--',
          'leoiOtherNameId': null,
          'aliasSearchInd': null,
          'canManageRelationship': true,
          'groupedRelationship': null,
          'services': 'Base Relationship',
          'country': '--',
          'formationStatusCd': 'ACTIVE',
          'formationStatusDesc': 'Active',
          'isNew': false,
          'serviceCd': 'BASE_REL',
          'sourceTypeCd': 'PROVIDER',
          'canInitiateServiceRequest': false
        }
      ],
      'services': '--',
      'country': '--',
      'formationStatusCd': 'ACTIVE',
      'formationStatusDesc': 'Active',
      'isNew': false,
      'serviceCd': null,
      'sourceTypeCd': 'PROVIDER',
      'canInitiateServiceRequest': false
    },
    {
      'serialNumber': 929,
      'rid': 76337460,
      'r2id': 76337500,
      'providerid': 7,
      'consumerid': 100000619,
      'leoiid': 119312729,
      'provider': 'Clarient',
      'consumer': 'State Street Global Advisors Limited',
      'leoi': '\'Interaktivnye technologii\' OOO',
      'status': 'Active',
      'isprovidertoleoi': null,
      'endDate': null,
      'canOfferAccess': false,
      'provConsInd': 'CONSUMER',
      'leoiOtherName': '--',
      'leoiOtherNameId': null,
      'aliasSearchInd': null,
      'canManageRelationship': true,
      'groupedRelationship': null,
      'services': 'Public KYC Premium',
      'country': '--',
      'formationStatusCd': null,
      'formationStatusDesc': null,
      'isNew': false,
      'serviceCd': 'PKYC_PREMIUM',
      'sourceTypeCd': 'PROVIDER',
      'canInitiateServiceRequest': true
    },
    {
      'serialNumber': 930,
      'rid': 76301060,
      'r2id': 76301110,
      'providerid': 7,
      'consumerid': 100000619,
      'leoiid': 119237069,
      'provider': 'Clarient',
      'consumer': 'State Street Global Advisors Limited',
      'leoi': '\'Kamchatprommet\' ZAO',
      'status': 'Active',
      'isprovidertoleoi': null,
      'endDate': null,
      'canOfferAccess': false,
      'provConsInd': 'CONSUMER',
      'leoiOtherName': '--',
      'leoiOtherNameId': null,
      'aliasSearchInd': null,
      'canManageRelationship': true,
      'groupedRelationship': null,
      'services': 'Public KYC Premium',
      'country': '--',
      'formationStatusCd': null,
      'formationStatusDesc': null,
      'isNew': false,
      'serviceCd': 'PKYC_PREMIUM',
      'sourceTypeCd': 'PROVIDER',
      'canInitiateServiceRequest': true
    },
    {
      'serialNumber': 931,
      'rid': 76289740,
      'r2id': 76289780,
      'providerid': 7,
      'consumerid': 100000619,
      'leoiid': 119214409,
      'provider': 'Clarient',
      'consumer': 'State Street Global Advisors Limited',
      'leoi': '\'Kampol - K. Humiński & Syn\' Spółka Z Ograniczoną Odpowiedzialnością',
      'status': 'Active',
      'isprovidertoleoi': null,
      'endDate': null,
      'canOfferAccess': false,
      'provConsInd': 'CONSUMER',
      'leoiOtherName': '--',
      'leoiOtherNameId': null,
      'aliasSearchInd': null,
      'canManageRelationship': true,
      'groupedRelationship': null,
      'services': 'Public KYC Premium',
      'country': '--',
      'formationStatusCd': null,
      'formationStatusDesc': null,
      'isNew': false,
      'serviceCd': 'PKYC_PREMIUM',
      'sourceTypeCd': 'PROVIDER',
      'canInitiateServiceRequest': true
    },
    {
      'serialNumber': 932,
      'rid': 76259520,
      'r2id': 76259560,
      'providerid': 7,
      'consumerid': 100000619,
      'leoiid': 119153709,
      'provider': 'Clarient',
      'consumer': 'State Street Global Advisors Limited',
      'leoi': '\'Kurier Lubelski\' Spółka Z Ograniczoną Odpowiedzialnością',
      'status': 'Active',
      'isprovidertoleoi': null,
      'endDate': null,
      'canOfferAccess': false,
      'provConsInd': 'CONSUMER',
      'leoiOtherName': '--',
      'leoiOtherNameId': null,
      'aliasSearchInd': null,
      'canManageRelationship': true,
      'groupedRelationship': null,
      'services': 'Public KYC Premium',
      'country': '--',
      'formationStatusCd': null,
      'formationStatusDesc': null,
      'isNew': false,
      'serviceCd': 'PKYC_PREMIUM',
      'sourceTypeCd': 'PROVIDER',
      'canInitiateServiceRequest': true
    },
    {
      'serialNumber': 933,
      'rid': 76318000,
      'r2id': 76318040,
      'providerid': 7,
      'consumerid': 100000619,
      'leoiid': 119272109,
      'provider': 'Clarient',
      'consumer': 'State Street Global Advisors Limited',
      'leoi': '\'Lupa\' Spółka Z Ograniczoną Odpowiedzialnością',
      'status': 'Active',
      'isprovidertoleoi': null,
      'endDate': null,
      'canOfferAccess': false,
      'provConsInd': 'CONSUMER',
      'leoiOtherName': '--',
      'leoiOtherNameId': null,
      'aliasSearchInd': null,
      'canManageRelationship': true,
      'groupedRelationship': null,
      'services': 'Public KYC Premium',
      'country': '--',
      'formationStatusCd': null,
      'formationStatusDesc': null,
      'isNew': false,
      'serviceCd': 'PKYC_PREMIUM',
      'sourceTypeCd': 'PROVIDER',
      'canInitiateServiceRequest': true
    },
    {
      'serialNumber': null,
      'rid': 76387770,
      'r2id': null,
      'providerid': 100000489,
      'consumerid': null,
      'leoiid': 120105159,
      'provider': 'IM C1',
      'consumer': '--',
      'leoi': '0001EvidenceTesting',
      'status': null,
      'isprovidertoleoi': null,
      'endDate': null,
      'canOfferAccess': false,
      'provConsInd': 'CONSUMER',
      'leoiOtherName': '--',
      'leoiOtherNameId': null,
      'aliasSearchInd': null,
      'canManageRelationship': null,
      'groupedRelationship': [
        {
          'serialNumber': 951,
          'rid': 76387770,
          'r2id': 76488260,
          'providerid': 100000489,
          'consumerid': 100000619,
          'leoiid': 120105159,
          'provider': 'IM C1',
          'consumer': 'State Street Global Advisors Limited',
          'leoi': '0001EvidenceTesting',
          'status': 'Active',
          'isprovidertoleoi': null,
          'endDate': null,
          'canOfferAccess': false,
          'provConsInd': 'CONSUMER',
          'leoiOtherName': '--',
          'leoiOtherNameId': null,
          'aliasSearchInd': null,
          'canManageRelationship': true,
          'groupedRelationship': null,
          'services': 'Base Relationship',
          'country': '--',
          'formationStatusCd': 'ACTIVE',
          'formationStatusDesc': 'Active',
          'isNew': false,
          'serviceCd': 'BASE_REL',
          'sourceTypeCd': 'PROVIDER',
          'canInitiateServiceRequest': true
        },
        {
          'serialNumber': 952,
          'rid': 76387770,
          'r2id': 76488260,
          'providerid': 100000489,
          'consumerid': 100000619,
          'leoiid': 120105159,
          'provider': 'IM C1',
          'consumer': 'State Street Global Advisors Limited',
          'leoi': '0001EvidenceTesting',
          'status': 'Active',
          'isprovidertoleoi': null,
          'endDate': null,
          'canOfferAccess': false,
          'provConsInd': 'CONSUMER',
          'leoiOtherName': '--',
          'leoiOtherNameId': null,
          'aliasSearchInd': null,
          'canManageRelationship': true,
          'groupedRelationship': null,
          'services': 'Public KYC',
          'country': '--',
          'formationStatusCd': 'ACTIVE',
          'formationStatusDesc': 'Active',
          'isNew': false,
          'serviceCd': 'PKYC',
          'sourceTypeCd': 'PROVIDER',
          'canInitiateServiceRequest': true
        }
      ],
      'services': '--',
      'country': '--',
      'formationStatusCd': 'ACTIVE',
      'formationStatusDesc': 'Active',
      'isNew': null,
      'serviceCd': null,
      'sourceTypeCd': null,
      'canInitiateServiceRequest': false
    },
    {
      'serialNumber': 765,
      'rid': 75851170,
      'r2id': null,
      'providerid': 100000619,
      'consumerid': null,
      'leoiid': 111351559,
      'provider': 'State Street Global Advisors Limited',
      'consumer': '--',
      'leoi': '01Jan_Sanity_Test',
      'status': 'Active',
      'isprovidertoleoi': 'Y',
      'endDate': null,
      'canOfferAccess': true,
      'provConsInd': 'PROVIDER',
      'leoiOtherName': '--',
      'leoiOtherNameId': null,
      'aliasSearchInd': null,
      'canManageRelationship': false,
      'groupedRelationship': [
        {
          'serialNumber': 10,
          'rid': 75851170,
          'r2id': 76047970,
          'providerid': 100000619,
          'consumerid': 100000569,
          'leoiid': 111351559,
          'provider': 'State Street Global Advisors Limited',
          'consumer': 'Bank AA2 LLC',
          'leoi': '01Jan_Sanity_Test',
          'status': 'Active',
          'isprovidertoleoi': 'N',
          'endDate': null,
          'canOfferAccess': false,
          'provConsInd': 'PROVIDER',
          'leoiOtherName': '--',
          'leoiOtherNameId': null,
          'aliasSearchInd': null,
          'canManageRelationship': true,
          'groupedRelationship': null,
          'services': 'Base Relationship',
          'country': '--',
          'formationStatusCd': 'ACTIVE',
          'formationStatusDesc': 'Active',
          'isNew': false,
          'serviceCd': 'BASE_REL',
          'sourceTypeCd': 'PROVIDER',
          'canInitiateServiceRequest': false
        },
        {
          'serialNumber': 11,
          'rid': 75851170,
          'r2id': 75851180,
          'providerid': 100000619,
          'consumerid': 100000599,
          'leoiid': 111351559,
          'provider': 'State Street Global Advisors Limited',
          'consumer': 'Bank E1',
          'leoi': '01Jan_Sanity_Test',
          'status': 'Active',
          'isprovidertoleoi': 'N',
          'endDate': null,
          'canOfferAccess': false,
          'provConsInd': 'PROVIDER',
          'leoiOtherName': '--',
          'leoiOtherNameId': null,
          'aliasSearchInd': null,
          'canManageRelationship': true,
          'groupedRelationship': null,
          'services': 'Full KYC',
          'country': 'United States of America',
          'formationStatusCd': 'ACTIVE',
          'formationStatusDesc': 'Active',
          'isNew': false,
          'serviceCd': 'FULL',
          'sourceTypeCd': 'PROVIDER',
          'canInitiateServiceRequest': false
        }
      ],
      'services': '--',
      'country': '--',
      'formationStatusCd': 'ACTIVE',
      'formationStatusDesc': 'Active',
      'isNew': false,
      'serviceCd': null,
      'sourceTypeCd': 'PROVIDER',
      'canInitiateServiceRequest': false
    },
    {
      'serialNumber': 953,
      'rid': 76299740,
      'r2id': 76299780,
      'providerid': 7,
      'consumerid': 100000619,
      'leoiid': 119234499,
      'provider': 'Clarient',
      'consumer': 'State Street Global Advisors Limited',
      'leoi': '0858065 BC Ltd',
      'status': 'Active',
      'isprovidertoleoi': null,
      'endDate': null,
      'canOfferAccess': false,
      'provConsInd': 'CONSUMER',
      'leoiOtherName': '--',
      'leoiOtherNameId': null,
      'aliasSearchInd': null,
      'canManageRelationship': true,
      'groupedRelationship': null,
      'services': 'Public KYC Premium',
      'country': '--',
      'formationStatusCd': null,
      'formationStatusDesc': null,
      'isNew': false,
      'serviceCd': 'PKYC_PREMIUM',
      'sourceTypeCd': 'PROVIDER',
      'canInitiateServiceRequest': true
    },
    {
      'serialNumber': null,
      'rid': 75793390,
      'r2id': null,
      'providerid': 100000569,
      'consumerid': null,
      'leoiid': 100098489,
      'provider': 'Bank AA2 LLC',
      'consumer': '--',
      'leoi': '0912 Ivv Test3',
      'status': null,
      'isprovidertoleoi': null,
      'endDate': null,
      'canOfferAccess': false,
      'provConsInd': 'CONSUMER',
      'leoiOtherName': '--',
      'leoiOtherNameId': null,
      'aliasSearchInd': null,
      'canManageRelationship': null,
      'groupedRelationship': [
        {
          'serialNumber': 954,
          'rid': 75793390,
          'r2id': 75793420,
          'providerid': 100000569,
          'consumerid': 100000629,
          'leoiid': 100098489,
          'provider': 'Bank AA2 LLC',
          'consumer': 'ABC Fund Manager 1',
          'leoi': '0912 Ivv Test3',
          'status': 'Active',
          'isprovidertoleoi': null,
          'endDate': null,
          'canOfferAccess': false,
          'provConsInd': 'CONSUMER',
          'leoiOtherName': '--',
          'leoiOtherNameId': null,
          'aliasSearchInd': null,
          'canManageRelationship': true,
          'groupedRelationship': null,
          'services': 'Base Relationship',
          'country': '--',
          'formationStatusCd': 'ACTIVE',
          'formationStatusDesc': 'Active',
          'isNew': false,
          'serviceCd': 'BASE_REL',
          'sourceTypeCd': 'PROVIDER',
          'canInitiateServiceRequest': true
        },
        {
          'serialNumber': 955,
          'rid': 75793390,
          'r2id': 75793420,
          'providerid': 100000569,
          'consumerid': 100000629,
          'leoiid': 100098489,
          'provider': 'Bank AA2 LLC',
          'consumer': 'ABC Fund Manager 1',
          'leoi': '0912 Ivv Test3',
          'status': 'Active',
          'isprovidertoleoi': null,
          'endDate': null,
          'canOfferAccess': false,
          'provConsInd': 'CONSUMER',
          'leoiOtherName': '--',
          'leoiOtherNameId': null,
          'aliasSearchInd': null,
          'canManageRelationship': true,
          'groupedRelationship': null,
          'services': 'Base Relationship',
          'country': '--',
          'formationStatusCd': 'ACTIVE',
          'formationStatusDesc': 'Active',
          'isNew': false,
          'serviceCd': 'BASE_REL',
          'sourceTypeCd': 'PROVIDER',
          'canInitiateServiceRequest': true
        }
      ],
      'services': '--',
      'country': '--',
      'formationStatusCd': 'ACTIVE',
      'formationStatusDesc': 'Active',
      'isNew': null,
      'serviceCd': null,
      'sourceTypeCd': null,
      'canInitiateServiceRequest': false
    },
    {
      'serialNumber': 614,
      'rid': 76072050,
      'r2id': 76072070,
      'providerid': 100000629,
      'consumerid': 100000639,
      'leoiid': 116953709,
      'provider': 'ABC Fund Manager 1',
      'consumer': 'Bank I1',
      'leoi': 'Testing TP4164',
      'status': 'Active',
      'isprovidertoleoi': 'N',
      'endDate': null,
      'canOfferAccess': false,
      'provConsInd': 'PROVIDER',
      'leoiOtherName': '--',
      'leoiOtherNameId': null,
      'aliasSearchInd': null,
      'canManageRelationship': true,
      'groupedRelationship': null,
      'services': 'Base Relationship',
      'country': '--',
      'formationStatusCd': 'ACTIVE',
      'formationStatusDesc': 'Active',
      'isNew': false,
      'serviceCd': 'BASE_REL',
      'sourceTypeCd': 'PROVIDER',
      'canInitiateServiceRequest': false
    },
    {
      'serialNumber': 615,
      'rid': 76072050,
      'r2id': 76072070,
      'providerid': 100000629,
      'consumerid': 100000639,
      'leoiid': 116953709,
      'provider': 'ABC Fund Manager 1',
      'consumer': 'Bank I1',
      'leoi': 'Testing TP4164',
      'status': 'Active',
      'isprovidertoleoi': 'N',
      'endDate': null,
      'canOfferAccess': false,
      'provConsInd': 'PROVIDER',
      'leoiOtherName': '--',
      'leoiOtherNameId': null,
      'aliasSearchInd': null,
      'canManageRelationship': true,
      'groupedRelationship': null,
      'services': 'Full KYC',
      'country': 'United States of America',
      'formationStatusCd': 'ACTIVE',
      'formationStatusDesc': 'Active',
      'isNew': false,
      'serviceCd': 'FULL',
      'sourceTypeCd': 'PROVIDER',
      'canInitiateServiceRequest': false
    },
    {
      'serialNumber': 612,
      'rid': 76072050,
      'r2id': 76072060,
      'providerid': 100000629,
      'consumerid': 7,
      'leoiid': 116953709,
      'provider': 'ABC Fund Manager 1',
      'consumer': 'Clarient',
      'leoi': 'Testing TP4164',
      'status': 'Active',
      'isprovidertoleoi': 'N',
      'endDate': null,
      'canOfferAccess': false,
      'provConsInd': 'PROVIDER',
      'leoiOtherName': '--',
      'leoiOtherNameId': null,
      'aliasSearchInd': null,
      'canManageRelationship': true,
      'groupedRelationship': null,
      'services': 'Public KYC Premium',
      'country': '--',
      'formationStatusCd': 'ACTIVE',
      'formationStatusDesc': 'Active',
      'isNew': false,
      'serviceCd': 'PKYC_PREMIUM',
      'sourceTypeCd': 'PROVIDER',
      'canInitiateServiceRequest': false
    },
    {
      'serialNumber': 616,
      'rid': 76072050,
      'r2id': 76072060,
      'providerid': 100000629,
      'consumerid': 7,
      'leoiid': 116953709,
      'provider': 'ABC Fund Manager 1',
      'consumer': 'Clarient',
      'leoi': 'Testing TP4164',
      'status': 'Active',
      'isprovidertoleoi': 'N',
      'endDate': null,
      'canOfferAccess': false,
      'provConsInd': 'PROVIDER',
      'leoiOtherName': '--',
      'leoiOtherNameId': null,
      'aliasSearchInd': null,
      'canManageRelationship': true,
      'groupedRelationship': null,
      'services': 'Base Relationship',
      'country': '--',
      'formationStatusCd': 'ACTIVE',
      'formationStatusDesc': 'Active',
      'isNew': false,
      'serviceCd': 'BASE_REL',
      'sourceTypeCd': 'PROVIDER',
      'canInitiateServiceRequest': false
    }
  ],
  'services': '--',
  'country': '--',
  'formationStatusCd': 'ACTIVE',
  'formationStatusDesc': 'Active',
  'isNew': false,
  'serviceCd': null,
  'sourceTypeCd': 'PROVIDER',
  'canInitiateServiceRequest': false
};
